version: '3'

services:
  reverseproxy:
    container_name: reverseproxy
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynet1
      - mynet2
  app1:
    container_name: frontserver
    build:
      context: ./app1
    volumes:
      - "./app1:/var/www/html"
    networks:
      - mynet1
  app2:
    container_name: dpserver # processing service
    build:
      context: ./app2
    volumes:
      - "./app2:/var/www/html"
    networks:
      - mynet2
networks:
  mynet1:
  mynet2: