version: "3"

services:
  myserver:
    image: httpd:latest
    container_name: myserver
    ports:
      - "8080:80"
    networks:
      - simplenw

  mycurlclient:
    image: curlimages/curl:latest
    container_name: mycurlclient
    networks:
      - simplenw
networks:
  simplenw: